language: rust

os: 
  - osx
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.34.0

script:
  
  - rustup install nightly

  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/impl/"
  - cargo +nightly build --release

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_0/"
  - cargo +nightly build --release

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_1/"
  - cargo +nightly build --release

  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/implementation/"
  - cargo +nightly build --release

  - cd "${TRAVIS_BUILD_DIR}/testing/impl_0/"
  - cargo +nightly build --release


  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/impl/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_0/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_1/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/implementation/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/testing/impl_0/"
  - cargo check


  - cd "${TRAVIS_BUILD_DIR}/abi_stable_derive_lib"
  - cargo test
  
  - cd "${TRAVIS_BUILD_DIR}/abi_stable"
  - cargo test --features sabi_trait_examples
  
  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/impl/"
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/user/"
  - cargo run --release -- run-tests
  
  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/application/"
  - cargo run --release

  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/implementation/"
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/user/"
  - cargo run --release
  - cd "${TRAVIS_BUILD_DIR}/testing/user/"
  - cargo run --release
