language: rust

os: 
  - osx
  - linux

matrix:
  include:
    # - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.39.0
  allow_failures:
    - rust: nightly

script:
  
  - rustup install beta

  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/impl/"
  - cargo +beta build

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_0/"
  - cargo +beta build

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_1/"
  - cargo +beta build

  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/implementation/"
  - cargo +beta build

  - cd "${TRAVIS_BUILD_DIR}/testing/0/impl_0/"
  - cargo +beta build
  
  - cd "${TRAVIS_BUILD_DIR}/testing/1 - loading errors/impl_1/"
  - cargo +beta build
  
  - cd "${TRAVIS_BUILD_DIR}/testing/1 - loading errors/non_abi_stable_lib/"
  - cargo +beta build
  
  - cd "${TRAVIS_BUILD_DIR}/testing/version_compatibility/impl_0"
  - cargo +beta build

  - cd "${TRAVIS_BUILD_DIR}/"
  - rm Cargo.lock

  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/impl/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_0/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/plugin_1/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/implementation/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/testing/0/impl_0/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/testing/1 - loading errors/impl_1/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/testing/1 - loading errors/non_abi_stable_lib/"
  - cargo check

  - cd "${TRAVIS_BUILD_DIR}/abi_stable"
  - cargo check --no-default-features

  - cd "${TRAVIS_BUILD_DIR}/abi_stable_derive"
  - cargo test
  
  - cd "${TRAVIS_BUILD_DIR}/abi_stable"
  - cargo test --features sabi_trait_examples
  
  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/impl/"
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/examples/0_modules_and_interface_types/user/"
  - cargo run -- run-tests
  
  - cd "${TRAVIS_BUILD_DIR}/examples/1_trait_objects/application/"
  - cargo run

  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/implementation/"
  - cargo test
  - cd "${TRAVIS_BUILD_DIR}/examples/2_nonexhaustive/user/"
  - cargo run
  - cd "${TRAVIS_BUILD_DIR}/testing/user_0/"
  - cargo run
  - cd "${TRAVIS_BUILD_DIR}/testing/1 - loading errors/user_1/"
  - env "RETURN_ERR=false" cargo run
  - env "RETURN_ERR=true" cargo run


  - cd "${TRAVIS_BUILD_DIR}/testing/version_compatibility/user_0"
  - cargo run
