language: rust

os: 
  - osx
  - linux

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.34.0

script:
  - cd "${TRAVIS_BUILD_DIR}/abi_stable"
  - cargo test --release
  
  - cd "${TRAVIS_BUILD_DIR}/examples/example_0_impl/"
  - cargo build --release
  - cargo test --release
  - cd "${TRAVIS_BUILD_DIR}/examples/example_0_user/"
  - cargo run --release -- run-tests
  
  - cd "${TRAVIS_BUILD_DIR}/testing/impl_0/"
  - cargo build --release
  - cd "${TRAVIS_BUILD_DIR}/testing/user/"
  - cargo run --release
