[package]
name = "abi_stable"
version = "0.6.3"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition="2018"
license = "MIT/Apache-2.0"
description = "For doing Rust-to-Rust ffi,writing libraries loaded at program startup."
documentation = "https://docs.rs/abi_stable/"
readme="../readme.md"
keywords = ["ffi","data-structures"]
categories = ["data-structures","rust-patterns"]
repository = "https://github.com/rodrimati1992/abi_stable_crates/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "../readme.md", 
    "../APACHE_license", 
    "../MIT_license"
]

[badges]
travis-ci = { repository =  "rodrimati1992/abi_stable_crates/" }

[features]
default = ["channels","serde_json"]

rust_1_34=[]

rust_1_36=[]

# Test features,only used internally.
only_new_tests=[]
sabi_trait_examples=[]

channels=["crossbeam-channel"]


[dependencies]
abi_stable_derive= {version="0.6.2",path="../abi_stable_derive"}
abi_stable_shared= {version="0.6.0",path="../abi_stable_shared"}
serde          = {version="1.0",features=["derive"]}
serde_derive   = "1.0"
core_extensions= { version="0.1"}
libloading     = { version = "0.5.0" }
parking_lot    = "0.7"
lock_api       = "0.1"
generational-arena = "0.2"
crossbeam-channel = {version="0.3",optional=true}
serde_json = {version="1.0",features=["raw_value"],optional=true}

[dev-dependencies]
bincode = "1.1"
crossbeam-utils = "0.6"
serde_json = {version="1.0",features=["raw_value"]}
rand = "0.6"
criterion = "0.2"
hashbrown = "0.3"
fnv = "1.0"
skeptic = "0.13"


[build-dependencies]
rustc_version = "0.2"
skeptic = "0.13"
