[package]
name = "abi_stable"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition="2018"
license = "MIT/Apache-2.0"
description = "For doing Rust-to-Rust ffi,focused on loading dynamic libraries at startup."
documentation = "https://docs.rs/abi_stable/"
readme="../readme.md"
keywords = ["typelevel", "no-std"]
categories = ["no-std"]
repository = "https://github.com/rodrimati1992/abi_stable_crates/"
include = [
    "Cargo.toml", 
    "src/**/*.rs", 
    "docs/**/*.rs", 
    "docs/**/*.md", 
    "../readme.md", 
    "../APACHE_license", 
    "../MIT_license"
]

[badges]
travis-ci = { repository =  "rodrimati1992/abi_stable_crates/" }

[features]
default = []

[dependencies]
abi_stable_derive= {version="0.1",path="../abi_stable_derive"}
abi_stable_derive_lib= {version="0.1",path="../abi_stable_derive_lib"}
serde          = "1.0"
serde_derive   = "1.0"
core_extensions= { version="0.1",path="../../crates/shared_extensions/core_extensions" }
libloading     = { version = "0.5.0" }
parking_lot    = "0.7"
lock_api       = "0.1"


[dev-dependencies]
serde_json     = "1.0"
