[package]
name = "abi_stable"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition="2018"

[features]
default = [
    "libloading",
]

[dependencies]
abi_stable_derive= {version="0.1",path="../abi_stable_derive"}
abi_stable_derive_lib= {version="0.1",path="../abi_stable_derive_lib"}
serde          = "1.0"
serde_derive   = "1.0"
core_extensions= { version="0.1",path="../../shared_extensions/core_extensions" }
libloading     = { version = "0.5.0" ,optional = true}


[dev-dependencies]
serde_json     = "1.0"
