[package]
name = "abi_stable_derive_lib"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6.11"
core_extensions= {version="0.1",path="../../crates/shared_extensions/core_extensions"}
lazy_static = "1.3"
typed-arena = "1.4"
proc-macro2 = "0.4"
arrayvec    = "0.4"
hashbrown = "0.1"

[dependencies.syn]
version = "0.15"
features=["full","extra-traits","visit","visit-mut"]
