[package]
name = "abi_stable_derive"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2018"

[dependencies]
abi_stable_derive_lib={version="0.1",path="../abi_stable_derive_lib"}

[lib]
proc-macro = true
